set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
set(VCPKG_MAKE_BUILD_TRIPLET "--host=armv7a-linux-androideabi")
set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-21)

set(ANDROID_NDK_HOME "/mnt/c/Users/Mehdi Mehdark/AppData/Local/Android/Sdk/ndk/android-ndk-r29")
set(ANDROID_SDK_ROOT "/mnt/c/Users/Mehdi Mehdark/AppData/Local/Android/Sdk")
set(VCPKG_ENV_PASSTHROUGH ANDROID_NDK_HOME ANDROID_SDK_ROOT)
